import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./Components";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col bg-white gap-[28px]`}
        suppressHydrationWarning={true}
      >
        <Header
          title={"Star Wars Characters"}
          body={`Lorem ipsum dolor sit amet, consectetur
                adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua.`}
        />

        {children}
      </body>
    </html>
  );
}
